version: "3.8"

services:  
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=pedro
      - MYSQL_PASSWORD=papiro
      - MYSQL_ROOT_PASSWORD=papiro
